export const flaskLessons=[
 {title:'1. Подготовьте каркас и файлы',why:'Форма не возникает сама: браузер получает HTML-шаблон, Flask принимает GET/POST, а обработчик читает или записывает таблицы. Начните с учебного каркаса: в нём уже есть подключение БД, сессия, CSRF и заглушки маршрутов. Затем заменяйте по одному помеченному блоку.',source:'Структура учебного примера; КИМ, стр. 33–34',files:['requirements.txt','templates/base.html'],check:'Установите зависимости по инструкции Windows. Запустите каркас: главная страница должна сообщить, что это учебный каркас. База должна создаться без ошибок.',key:null},
 {title:'2. Главная страница и каталог',why:'КИМ описывает выбор помещения. Для удобства примера сначала создаём каталог: Flask читает rooms и передаёт список в HTML. Это подготовит ссылки, которыми будут пользоваться формы.',source:'КИМ, стр. 33, 36; rooms → шаблоны каталога',key:'catalog',files:['templates/_room_card.html','templates/index.html','templates/rooms.html','templates/room_detail.html'],check:'Откройте / и /rooms: видны шесть помещений. Выбор помещения ведёт к заглушке будущей заявки — её заменим на шаге 6.'},
 {title:'3. Форма регистрации',why:'На странице 34 КИМ прямо перечислены поля регистрации. Создайте templates/register.html: name каждого input — ключ, который обработчик читает через request.form. GET показывает форму, POST проверяет значения и добавляет users. Пароль превращается в password_hash.',source:'КИМ, стр. 34, пункт 1 «Страница регистрации»',key:'register',files:['templates/register.html'],check:'Откройте /register, отправьте короткий логин: ошибка остаётся у поля, запись не создаётся. Успешный вход проверим после следующего шага.',map:'Логин → input name="username" → request.form → users.username. Аналогично: full_name, phone, email. password → generate_password_hash → users.password_hash; повтор пароля в БД не хранится.'},
 {title:'4. Форма входа и выход',why:'Страница 34 требует вход по логину и паролю. templates/login.html отправляет username/password; Flask находит users, проверяет хеш и записывает user_id в сессию. Кнопка выхода отправляет POST и очищает сессию.',source:'КИМ, стр. 34, пункт 2 «Страница авторизации»',key:'login',files:['templates/login.html'],check:'На /login введите неверный пароль: увидите сообщение. Личный кабинет пока заглушка; создайте его следующим шагом.',map:'username → SELECT users → check_password_hash → session["user_id"]. Сессия сообщает серверу, кому принадлежат будущие заявки.'},
 {title:'5. Личный кабинет',why:'Фраза «свои ранее оставленные заявки» требует отбора по текущему пользователю. Создайте templates/dashboard.html, затем обработчик /dashboard: он соединяет applications с rooms и ограничивает выборку WHERE user_id = текущий пользователь.',source:'КИМ, стр. 34, пункт 3 «Страница просмотра заявок»',key:'dashboard',files:['templates/dashboard.html'],check:'Зарегистрируйте обычного пользователя, войдите. Откроется пустой кабинет. Ссылки создания заявки и отзыва реализуем далее.',map:'session.user_id → g.user.id → WHERE applications.user_id = ?. В кабинет не должны попадать чужие заявки.'},
 {title:'6. Форма новой заявки',why:'КИМ требует помещение, дату и оплату; описание также указывает предпочтительное время. HTML получает rooms для select, а POST сохраняет выбранный room_id. Владельца и новый статус определяет сервер. Название конференции и число участников — дополнения примера.',source:'КИМ, стр. 33–34, пункт 4; стр. 36 — выпадающие списки',key:'application',files:['templates/application_form.html'],check:'Откройте /applications/new под пользователем. После отправки заявка должна появиться в кабинете со статусом «Новая». Проверьте неправильную дату и вместимость.',map:'select name="room_id" → проверка rooms.id → applications.room_id. event_date/start_time/payment_method → одноимённые поля; g.user.id → user_id.'},
 {title:'7. Панель администратора и статусы',why:'По КИМ администратор видит все заявки и меняет статус. Создайте templates/admin.html. GET /admin собирает список и фильтры, POST /admin/applications/<id>/status обновляет одну запись. @admin_required проверяет роль на сервере.',source:'КИМ, стр. 35, пункт 5; стр. 36 — улучшение панели',key:'admin',files:['templates/admin.html'],check:'Войдите как Conf2027 / Demo77. Назначьте, затем завершите мероприятие. В кабинете пользователя должен измениться статус. Обычный пользователь получает запрет доступа к /admin.',map:'select name="status" → STATUS_LABELS → UPDATE applications SET status = ?. id заявки приходит из адреса, роль — из users.is_admin.'},
 {title:'8. Отзыв о завершённой заявке',why:'Форма отзыва уже находится в templates/dashboard.html внутри карточки заявки. Теперь добавьте её POST-обработчик. Он проверяет владельца и completed до INSERT reviews; скрыть кнопку на странице недостаточно.',source:'КИМ, стр. 34 и 36 — отзыв после завершения',key:'review',files:['templates/dashboard.html'],check:'После завершения заявки отправьте отзыв. Повторный отзыв, чужая заявка и незавершённое мероприятие не должны принимать запись.',map:'Карточка заявки → application_id; сессия → user_id; textarea name="comment" → reviews.comment. rating — дополнительная оценка примера.'},
 {title:'9. Проверьте сборку и сохраните Git',why:'Все заглушки заменены. Теперь приложение должно повторять готовый пример: формы, сервер и база работают вместе. Сверьте файлы, выполните тесты, сохраните ER и инструкцию запуска, затем сделайте коммит и отправьте результат в свой репозиторий.',source:'КИМ, стр. 33, 36–37; tests/test_app.py',key:null,files:['tests/test_app.py'],check:'Выполните python -m pytest -q. Пройдите регистрацию → вход → заявку → смену статуса → отзыв. Затем git status, git add, git commit и git push.'}
];

export function assembly(code){
 const text=code['app.py'];
 const between=(start,end)=>{const a=text.indexOf(start),b=text.indexOf(end,a+start.length);if(a<0||b<0)throw Error('Assembly anchor missing: '+start);return {file:'app.py',start:text.slice(0,a).split('\n').length,text:text.slice(a,b).trimEnd()};};
 const routes={
  index:between('@bp.get("/")','@bp.route("/register"'),
  register:between('@bp.route("/register"','@bp.route("/login"'),
  login:between('@bp.route("/login"','@bp.get("/rooms")'),
  rooms:between('@bp.get("/rooms")','@bp.get("/dashboard")'),
  dashboard:between('@bp.get("/dashboard")','def _application_form_values()'),
  application:between('def _application_form_values()','@bp.post("/applications/<int:application_id>/review")'),
  review:between('@bp.post("/applications/<int:application_id>/review")','@bp.get("/admin")'),
  admin:between('@bp.get("/admin")','if __name__ == "__main__":')
 };
 const grouped={catalog:[routes.index,routes.rooms],register:[routes.register],login:[routes.login],dashboard:[routes.dashboard],application:[routes.application],admin:[routes.admin],review:[routes.review]};
 const names={catalog:['index','rooms'],register:['register'],login:['login'],dashboard:['dashboard'],application:['application'],admin:['admin'],review:['review']};
 const lessons=flaskLessons.map(x=>({...x,blocks:[...x.files.map(f=>({file:f,start:1,text:code[f],where:'Создайте файл по этому пути или замените его содержимое целиком. На шаге 8 dashboard.html уже создан: повторно менять его не нужно.'})),...(grouped[x.key]||[]).map((b,i)=>({...b,where:'В app.py замените весь участок между # BEGIN '+names[x.key][i]+' и # END '+names[x.key][i]+'. Самих строк-маркеров не удаляйте. Отступы и декораторы входят в фрагмент.'}))]}));
 let starter=text;
 for(const [name,b] of Object.entries(routes)){
  const headers=[...b.text.matchAll(/^((?:@[^\n]+\n)+def [^\n]+\n)/gm)].map(m=>m[1]);
  if(!headers.length)throw Error('No handlers: '+name);
  const stub=headers.map(h=>h+'    return "Учебный каркас: '+name+'. Выполните соответствующий шаг раздела Формы и Flask."\n').join('\n');
  starter=starter.replace(b.text,'# BEGIN '+name+'\n'+stub+'# END '+name);
 }
 return {lessons,starter};
}
